// nikukyu-web/src/pages/Home.tsx
import {Button} from "@nextui-org/react";

export function Home() {
    return (
        <div className={"h-screen w-screen bg-green-100 flex flex-col gap-2 justify-center items-center"}>
            <p className={"text-2xl text-green-500"}>🍀 This is Nikukyu, A Open Source SSO （Single Sign-On) software.</p>
            <div className={"flex flex-row gap-3"}>
                <Button className={"bg-green-400"} variant="shadow">Get Started</Button>
                <Button className={"bg-green-300"}>Document</Button>
                <Button className={"bg-green-300"}>Open Source</Button>
            </div>
        </div>
    )
}

// nikukyu-web/src/pages/Home.vue
<script lang="ts" setup>
import Button from "../components/Button.vue";
</script>
<template>
  <div class="h-[100vh] w-[100vw] flex flex-col gap-6 justify-center items-center">
    <p class="text-green-400 text-4xl">🍀 This is Nikukyu, A Open Source SSO （Single Sign-On) software.</p>
    <div class="flex gap-3">
      <Button type="message">Get Started</Button>
      <Button type="message">Open Source</Button>
      <Button type="message">Document</Button>
    </div>
  </div>
</template>
