// nikukyu-web/src/pages/Login.tsx
import {Button, Input} from "@nextui-org/react";

export function Login() {
    return (
        <div className="w-screen h-screen flex justify-center items-center bg-green-100">
            <div className="w-screen h-screen sm:w-[420px] sm:h-auto bg-white rounded-2xl p-12 flex flex-col gap-3">
                <p className="text-2xl">Login Nests ID</p>
                <div>
                    <p className="text-sm text-gray-500">Unregistered email addresses will automatically be used to
                        register a new
                        account.</p>
                    <p className="text-sm text-gray-500">This means you have agreed to our
                        <a className="text-sm text-green-500"> Privacy Policy </a>
                        and
                        <a className="text-sm text-green-500"> Terms of Use </a>
                    </p>
                </div>
                <Input className="" type="email" label="Email" placeholder="email / account id"/>
                <Button className="bg-green-300">Login</Button>
                <Button className="bg-black text-white">
                    <img src={"github-mark.svg"} className="scale-50" alt="Login with Github"/>
                    Login with Github
                </Button>
            </div>
        </div>
    )
}

// nikukyu-web/src/pages/Login.vue
<script lang="ts" setup>
import Panel from "../components/Panel.vue";
import Button from "../components/Button.vue";
import Input from "../components/Input.vue";
import OAuth from "../components/OAuth.vue";

const logins = [
  {icon: 'resources/images/icons8-github.svg', color: '#24292f', scale: '1.5', api: '', name: 'QQ Login'},
  {icon: 'resources/images/icons8-discord.svg', color: '#6C19ff', scale: '1.5', api: '', name: 'QQ Login'},
  {icon: 'resources/images/icons8-qq.svg', color: '#dcfce7', scale: '1.5', api: '', name: 'QQ Login'},
  {icon: 'resources/images/icons8-weibo.svg', color: '#dcfce7', scale: '1.5', api: '', name: 'QQ Login'},
  {icon: 'resources/images/icons8-baidu.svg', color: '#dcfce7', scale: '1.5', api: '', name: 'QQ Login'},
  {icon: 'resources/images/icons8-google.svg', color: '#dcfce7', scale: '1.5', api: '', name: 'QQ Login'},
  {icon: 'resources/images/icons8-microsoft.svg', color: '#dcfce7', scale: '1.5', api: '', name: 'QQ Login'},
]
</script>
<template>
  <div class="h-full w-full flex justify-center items-center">
    <div class="h-full w-full flex flex-row justify-center items-center backdrop-blur-3xl">
      <Panel class="flex flex-col gap-3">
        <p class="text-2xl">Login Nests ID</p>
        <div class="w-[320px]">
          <p class="text-sm text-gray-500">Unregistered email addresses will automatically be used to register a new
            account.</p>
          <div class="flex flex-row flex-wrap gap-1">
            <p class="text-sm text-gray-500">This means you have agreed to our</p>
            <a class="text-sm text-green-500">Privacy Policy</a>
            <p class="text-sm text-gray-500">and</p>
            <a class="text-sm text-green-500">Terms of Use</a>
          </div>
        </div>
        <Input class="w-[320px]" placeholder="Email / Account ID / Username"/>
        <div class="flex flex-row flex-wrap gap-2 w-[323px]">
          <Button class="w-[124px]" type="success">Login</Button>
          <OAuth v-for="login in logins" :style="{ backgroundColor: login.color }">
            <img :alt="login.name"
                 :src="login.icon"
                 :style="{width: `${login.scale}rem`, height: `${login.scale}rem`}"
            />
          </OAuth>
        </div>
      </Panel>
    </div>
  </div>
</template>
